name: musicbot
services:
  - name: musicbot
    image: python:3.9-slim
    ports:
      - port: 8080
        protocol: http
    env:
      - name: API_ID
        secret: true
      - name: API_HASH
        secret: true
      - name: BOT_TOKEN
        secret: true
      - name: PYTHON_VERSION
        value: "3.9"
    build:
      command: |
        apt-get update
        apt-get install -y python3.9 python3.9-dev python3-pip python3-setuptools build-essential \
          libjpeg-dev zlib1g-dev libffi-dev libssl-dev
        python3.9 -m pip install --upgrade pip
        python3.9 -m pip install wheel setuptools
        python3.9 -m pip install --no-cache-dir --only-binary :all: -r requirements-koyeb.txt
    run:
      command: python3.9 -m FallenMusic 