name: musicbot
services:
  - name: musicbot
    image: python:3.9
    ports:
      - port: 8080
        protocol: http
    env:
      - name: API_ID
        secret: true
      - name: API_HASH
        secret: true
      - name: BOT_TOKEN
        secret: true
      - name: PYTHON_VERSION
        value: "3.9"
    build:
      command: |
        apt-get update
        apt-get install -y python3-dev python3-pip python3-setuptools build-essential
        pip install --upgrade pip
        pip install wheel
        pip install --no-cache-dir -r requirements-koyeb.txt
    run:
      command: python -m FallenMusic 